AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AttiniDeploymentPlan
  - AWS::Serverless-2016-10-31

Parameters:
  AttiniEnvironmentName:
    Type: String

Resources:

  EchoLambdaDeploymentPlan:
    Type: Attini::Deploy::DeploymentPlan
    Properties:
      DeploymentPlan:
        - Name: DeploySamProject
          Type: AttiniSam
          Properties:
            Project:
              Path: /hello-world-app
            StackName: !Sub ${AttiniEnvironmentName}-sam-lambda
